import RichTextEditor from "reactjs-tiptap-editor"
// import { BaseKit } from 'reactjs-tiptap-editor';
import { useState } from "react"
import {
  BaseKit,
  Blockquote,
  Bold,
  BulletList,
  Clear,
  Code,
  CodeBlock,
  Color,
  Emoji,
  FontFamily,
  FontSize,
  FormatPainter,
  Heading,
  Highlight,
  History,
  HorizontalRule,
  Iframe,
  Image,
  Indent,
  Italic,
  LineHeight,
  Link,
  MoreMark,
  MultiColumn,
  OrderedList,
  SearchAndReplace,
  SlashCommand,
  Strike,
  SubAndSuperScript,
  Table,
  TableOfContents,
  TaskList,
  TextAlign,
  Underline,
} from "reactjs-tiptap-editor/extension-bundle" // for version 0.1.16 and lower

// Import CSS
import "reactjs-tiptap-editor/style.css"

import { useTranslation } from "@compo/localize"
import { locale } from "reactjs-tiptap-editor/locale-bundle"

locale.setMessage("fr", {
  "editor.remove": "Supprimer",
  "editor.copy": "Copier",
  "editor.words": "Mots",
  "editor.characters": "Caractères",
  "editor.default": "Default",
  "editor.recent": "Recent",
  "editor.nofill": "No fill",
  "editor.format": "Format",
  "editor.delete": "Supprimer",
  "editor.edit": "Modifier",
  "editor.settings": "Paramètres",
  "editor.table_of_content": "Table des matières",
  "editor.draghandle.tooltip": "Glisser-déposer",
  "editor.copyToClipboard": "Copier dans le presse-papiers",
  "editor.slash": "Slash",
  "editor.slash.empty": "Slash vide",
  "editor.slash.format": "Format du slash",
  "editor.slash.insert": "Insérer un slash",
  "editor.slash.embed": "Embed",
  "editor.content": "Contenu",
  "editor.fontFamily.tooltip": "Police de caractères",
  "editor.fontFamily.default.tooltip": "Police de caractères par défaut",
  "editor.moremark": "Plus de marques",
  "editor.size.small.tooltip": "Taille petite",
  "editor.size.medium.tooltip": "Taille moyenne",
  "editor.size.large.tooltip": "Taille grande",
  "editor.bold.tooltip": "Gras",
  "editor.italic.tooltip": "Italique",
  "editor.underline.tooltip": "Souligné",
  "editor.strike.tooltip": "Barré",
  "editor.color.tooltip": "Couleur",
  "editor.color.more": "Plus de couleurs",
  "editor.highlight.tooltip": "Highlight",
  "editor.lineheight.tooltip": "Hauteur de ligne",
  "editor.heading.tooltip": "Titre",
  "editor.heading.h1.tooltip": "Titre 1",
  "editor.heading.h2.tooltip": "Titre 2",
  "editor.heading.h3.tooltip": "Titre 3",
  "editor.heading.h4.tooltip": "Titre 4",
  "editor.heading.h5.tooltip": "Titre 5",
  "editor.heading.h6.tooltip": "Titre 6",
  "editor.paragraph.tooltip": "Paragraphe",
  "editor.textalign.tooltip": "Alignement",
  "editor.textalign.left.tooltip": "Alignement gauche",
  "editor.textalign.center.tooltip": "Alignement centré",
  "editor.textalign.right.tooltip": "Alignement droit",
  "editor.textalign.justify.tooltip": "Alignement justifié",
  "editor.indent": "Indentation",
  "editor.indent.indent": "Indentation",
  "editor.indent.outdent": "Désindentation",
  "editor.fontSize.tooltip": "Taille de la police",
  "editor.fontSize.default.tooltip": "Taille de la police par défaut",
  "editor.superscript.tooltip": "Exposant",
  "editor.subscript.tooltip": "Indice",
  "editor.bulletlist.tooltip": "Liste à puces",
  "editor.orderedlist.tooltip": "Liste numérotée",
  "editor.tasklist.tooltip": "Liste de tâches",
  "editor.indent.tooltip": "Indentation",
  "editor.outdent.tooltip": "Désindentation",
  "editor.columns.tooltip": "Colonnes",
  "editor.link.tooltip": "Lien",
  "editor.link.unlink.tooltip": "Supprimer le lien",
  "editor.link.open.tooltip": "Ouvrir le lien",
  "editor.link.edit.tooltip": "Modifier le lien",
  "editor.link.dialog.title": "Titre du lien",
  "editor.link.dialog.link": "Lien",
  "editor.link.dialog.text": "Texte",
  "editor.link.dialog.openInNewTab": "Ouvrir dans un nouvel onglet",
  "editor.link.dialog.link.placeholder": "Lien",
  "editor.link.dialog.text.placeholder": "Texte",
  "editor.link.dialog.button.apply": "Appliquer",
  "editor.image.tooltip": "Image",
  "editor.image.dragger.tooltip": "Glisser-déposer",
  "editor.image.float.left.tooltip": "Alignement gauche",
  "editor.image.float.none.tooltip": "Alignement normal",
  "editor.image.float.right.tooltip": "Alignement droit",
  "editor.image.dialog.title": "Titre de l'image",
  "editor.image.dialog.tab.url": "URL",
  "editor.image.dialog.tab.upload": "Télécharger",
  "editor.link.dialog.inline": "Inline",
  "editor.image.dialog.tab.uploadCrop": "Télécharger et couper",
  "editor.image.dialog.uploading": "Téléchargement",
  "editor.image.dialog.form.link": "Lien",
  "editor.image.dialog.placeholder": "Placeholder",
  "editor.image.dialog.form.alt": "Alt",
  "editor.image.dialog.form.aspectRatio": "Ratio",
  "editor.image.dialog.form.file": "Fichier",
  "editor.image.dialog.button.apply": "Appliquer",
  "editor.video.tooltip": "Vidéo",
  "editor.video.dialog.tab.upload": "Télécharger",
  "editor.video.dialog.uploading": "Téléchargement",
  "editor.video.dialog.title": "Titre de la vidéo",
  "editor.video.dialog.link": "Lien",
  "editor.video.dialog.placeholder": "Placeholder",
  "editor.video.dialog.button.apply": "Appliquer",
  "editor.table.tooltip": "Tableau",
  "editor.table.menu.insert_table": "Insérer un tableau",
  "editor.table.menu.insert_table.with_header_row": "Insérer un tableau avec une ligne d'en-tête",
  "editor.table.menu.add_column_before": "Ajouter une colonne avant",
  "editor.table.menu.add_column_after": "Ajouter une colonne après",
  "editor.table.menu.delete_column": "Supprimer une colonne",
  "editor.table.menu.add_row_before": "Ajouter une ligne avant",
  "editor.table.menu.add_row_after": "Ajouter une ligne après",
  "editor.table.menu.delete_row": "Supprimer une ligne",
  "editor.table.menu.merge_or_split_cells": "Fusionner ou diviser les cellules",
  "editor.table.menu.delete_table": "Supprimer le tableau",
  "editor.blockquote.tooltip": "Citation",
  "editor.horizontalrule.tooltip": "Ligne horizontale",
  "editor.code.tooltip": "Code",
  "editor.codeblock.tooltip": "Code bloc",
  "editor.clear.tooltip": "Effacer",
  "editor.undo.tooltip": "Annuler",
  "editor.redo.tooltip": "Rédo",
  "editor.fullscreen.tooltip.fullscreen": "Plein écran",
  "editor.fullscreen.tooltip.exit": "Sortir du plein écran",
  "editor.imageUpload.cancel": "Annuler",
  "editor.imageUpload.crop": "Couper",
  "editor.imageUpload.fileTypeNotSupported": "Type de fichier non supporté",
  "editor.imageUpload.fileSizeTooBig": "Taille du fichier trop grande",
  "editor.table.menu.insertColumnBefore": "Ajouter une colonne avant",
  "editor.table.menu.insertColumnAfter": "Ajouter une colonne après",
  "editor.table.menu.deleteColumn": "Supprimer une colonne",
  "editor.table.menu.insertRowAbove": "Ajouter une ligne au-dessus",
  "editor.table.menu.insertRowBelow": "Ajouter une ligne au-dessous",
  "editor.table.menu.deleteRow": "Supprimer une ligne",
  "editor.table.menu.mergeCells": "Fusionner les cellules",
  "editor.table.menu.splitCells": "Diviser les cellules",
  "editor.table.menu.deleteTable": "Supprimer le tableau",
  "editor.table.menu.setCellsBgColor": "Définir la couleur de fond des cellules",
  "editor.emoji.tooltip": "Emoji",
  "editor.iframe.tooltip": "Iframe",
  "editor.searchAndReplace.tooltip": "Rechercher et remplacer",
  "editor.search.dialog.text": "Rechercher",
  "editor.replace.dialog.text": "Remplacer",
  "editor.replaceAll.dialog.text": "Remplacer tout",
  "editor.previous.dialog.text": "Précédent",
  "editor.next.dialog.text": "Suivant",
  no_result_found: "Aucun résultat trouvé",
  "Smileys & People": "Smileys & People",
  "Animals & Nature": "Animals & Nature",
  "Food & Drink": "Food & Drink",
  Activity: "Activity",
  "Travel & Places": "Travel & Places",
  Object: "Object",
  Symbol: "Symbol",
  Flags: "Flags",
  "Frequently used": "Frequently used",
  "editor.formula.dialog.text": "Formula",
  "editor.katex.tooltip": "Katex",
  "editor.exportPdf.tooltip": "Export PDF",
  "editor.exportWord.tooltip": "Export Word",
  "editor.importWord.tooltip": "Import Word",
  "editor.importWord.limitSize": "Import Word limit size",
  "editor.importWord.converting": "Import Word converting",
  "editor.importWord.convertError": "Import Word convert error",
  "editor.importWord.importError": "Import Word import error",
  "editor.textDirection.tooltip": "Text direction",
  "editor.textDirection.auto.tooltip": "Text direction auto",
  "editor.textDirection.ltr.tooltip": "Text direction left to right",
  "editor.textDirection.rtl.tooltip": "Text direction right to left",
  "editor.attachment.tooltip": "Attachment",
  "editor.attachment.uploading": "Attachment uploading",
  "editor.attachment.please_upload": "Attachment please upload",
  "editor.imageGif.tooltip": "Image GIF",
  "editor.replace.caseSensitive": "Replace case sensitive",
  "editor.mermaid.tooltip": "Mermaid",
  "editor.twitter.tooltip": "Twitter",
  "editor.tooltip.flipX": "Flip X",
  "editor.tooltip.flipY": "Flip Y",
})

const extensions = [
  BaseKit.configure({
    // Show placeholder
    placeholder: {
      placeholder: "Écrivez quelque chose...",
      showOnlyCurrent: true,
    },

    // Character count
    characterCount: {
      // limit: 50_000,
    },
    selection: {},
  }),
  // Import Extensions Here
  Blockquote,
  Bold,
  BulletList,
  Clear,
  Code,
  CodeBlock,
  Color,
  FontSize,
  FontFamily,
  FormatPainter,
  Heading,
  Highlight,
  History,
  HorizontalRule,
  Iframe,
  Image,
  Indent,
  Italic,
  LineHeight,
  Link,
  MoreMark,
  MultiColumn,
  OrderedList,
  SlashCommand,
  Strike,
  SubAndSuperScript,
  Table,
  TaskList,
  TextAlign,
  Underline,
  SearchAndReplace,
  Emoji,
  TableOfContents,
]

const DEFAULT = ""

export const Example: React.FC = () => {
  const { language } = useTranslation()
  locale.setLang(language)
  const [content, setContent] = useState(DEFAULT)

  const onChangeContent = (value: any) => {
    setContent(value)
  }

  return (
    <div className='relative isolate'>
      <RichTextEditor output='html' content={content} onChangeContent={onChangeContent} extensions={extensions} />
      <pre>{content}</pre>
    </div>
  )
}
