/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const React: typeof import('react')['default']
  const cx: typeof import('class-variance-authority')['cx']
  const cxm: typeof import('tailwind-merge')['twMerge']
  const match: typeof import('ts-pattern')['match']
}
